baseURL: "https://www.comunidaddemamas.com"
languageCode: "es-cl"
title: "Comunidad de Mamás"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
disqusShortname: comunidaddemamas
taxonomies:
  author: authors
